/**
 * Seed data for the prototype.
 *
 * Chosen to be recognisable to anyone who works in the Indian official
 * statistical system - the divisions, roles, competencies and courses are the real
 * shape of the problem, not lorem ipsum. Two properties matter for a demo:
 *
 *  - The competency framework is a genuine role -> competency -> level matrix, so
 *    the gap engine has something defensible to compute against.
 *  - Officer levels are generated from per-division strength profiles rather than
 *    at random, so the heatmap shows structure (a National Accounts division that
 *    is strong on domain work and weak on digital) instead of a noise grid.
 */

export const departments = [
  { code: 'NSO_SDRD', name: 'Survey Design & Research Division', priority: 0.8, headcount: 120 },
  { code: 'NSO_FOD', name: 'Field Operations Division', priority: 0.7, headcount: 4200 },
  { code: 'NSO_NAD', name: 'National Accounts Division', priority: 0.9, headcount: 180 },
  { code: 'NSO_PCLD', name: 'Prices & Cost of Living Division', priority: 0.6, headcount: 90 },
  { code: 'NSO_ESD', name: 'Economic Statistics Division', priority: 0.7, headcount: 210 },
  { code: 'DES_MH', name: 'State DES — Maharashtra', priority: 0.85, headcount: 340 },
  { code: 'DES_OD', name: 'State DES — Odisha', priority: 0.85, headcount: 260 },
  { code: 'NSSTA', name: 'National Statistical Systems Training Academy', priority: 0.5, headcount: 60 },
];

export const competencies = [
  // Domain
  { code: 'SURVEY_DESIGN', name: 'Survey Design and Sampling', category: 'domain', futureDemand: 0.8, nsqfLevel: 7,
    description: 'Frame construction, sampling design, estimation procedures and non-response treatment for large-scale surveys.',
    tags: ['sampling', 'survey', 'frame', 'estimation'] },
  { code: 'NAT_ACCOUNTS', name: 'National Accounts Compilation', category: 'domain', futureDemand: 0.7, nsqfLevel: 8,
    description: 'GDP and GVA estimation, SNA 2008 concepts, supply-use tables and back-series construction.',
    tags: ['gdp', 'sna', 'national accounts', 'gva'] },
  { code: 'PRICE_STATS', name: 'Price Statistics and Index Numbers', category: 'domain', futureDemand: 0.6, nsqfLevel: 7,
    description: 'CPI and WPI construction, base revision, weighting diagrams and quality adjustment.',
    tags: ['cpi', 'wpi', 'index numbers', 'inflation'] },
  { code: 'ECON_STATS', name: 'Industrial and Economic Statistics', category: 'domain', futureDemand: 0.6, nsqfLevel: 7,
    description: 'ASI, IIP and the economic census: business registers, classification and response management.',
    tags: ['asi', 'iip', 'economic census', 'nic'] },
  { code: 'CENSUS_OPS', name: 'Large-Scale Enumeration Operations', category: 'domain', futureDemand: 0.5, nsqfLevel: 6,
    description: 'Planning and running field enumeration: listing, schedules, supervision and quality checks.',
    tags: ['census', 'enumeration', 'field', 'schedule'] },
  { code: 'SDG_MONITOR', name: 'SDG Indicator Monitoring', category: 'domain', futureDemand: 0.9, nsqfLevel: 7,
    description: 'National Indicator Framework: metadata, data source mapping, disaggregation and reporting.',
    tags: ['sdg', 'nif', 'indicators', 'metadata'] },
  { code: 'DATA_QUALITY', name: 'Data Quality Assurance', category: 'domain', futureDemand: 0.8, nsqfLevel: 6,
    description: 'Edit rules, consistency checks, outlier treatment and the NQAF quality dimensions.',
    tags: ['quality', 'validation', 'editing', 'nqaf'] },

  // Technical
  { code: 'STAT_INFERENCE', name: 'Statistical Inference and Estimation', category: 'technical', futureDemand: 0.7, nsqfLevel: 7,
    description: 'Estimators, variance estimation, confidence intervals and hypothesis testing for complex designs.',
    tags: ['inference', 'variance', 'estimator', 'testing'] },
  { code: 'TIME_SERIES', name: 'Time Series and Seasonal Adjustment', category: 'technical', futureDemand: 0.8, nsqfLevel: 8,
    description: 'ARIMA modelling, X-13 seasonal adjustment, benchmarking and revision analysis.',
    tags: ['time series', 'arima', 'seasonal adjustment', 'x13'] },
  { code: 'SMALL_AREA', name: 'Small Area Estimation', category: 'technical', futureDemand: 0.9, nsqfLevel: 8,
    description: 'Model-based estimation for domains the sample cannot support directly.',
    tags: ['small area', 'sae', 'model based', 'district'] },
  { code: 'DATA_INTEGRATION', name: 'Administrative Data Integration', category: 'technical', futureDemand: 0.9, nsqfLevel: 7,
    description: 'Record linkage, deduplication and combining administrative registers with survey data.',
    tags: ['record linkage', 'administrative data', 'integration'] },

  // Digital
  { code: 'STAT_PROG', name: 'Statistical Programming (R / Python)', category: 'digital', futureDemand: 0.9, nsqfLevel: 6,
    description: 'Reproducible analysis scripts, tabulation pipelines and version control.',
    tags: ['r', 'python', 'programming', 'reproducible'] },
  { code: 'DATA_VIZ', name: 'Data Visualisation and Dissemination', category: 'digital', futureDemand: 0.8, nsqfLevel: 6,
    description: 'Dashboards, statistical releases and accessible presentation of official figures.',
    tags: ['visualisation', 'dashboard', 'dissemination', 'charts'] },
  { code: 'GEOSPATIAL', name: 'Geospatial Analysis and Mapping', category: 'digital', futureDemand: 0.8, nsqfLevel: 6,
    description: 'GIS frames, geocoding, spatial joins and map-based dissemination.',
    tags: ['gis', 'geospatial', 'mapping', 'qgis'] },
  { code: 'BIG_DATA', name: 'Alternative Data Sources', category: 'digital', futureDemand: 0.95, nsqfLevel: 7,
    description: 'Web-scraped prices, satellite imagery, mobility and transaction data as statistical inputs.',
    tags: ['big data', 'alternative data', 'scraping', 'satellite'] },
  { code: 'DATA_GOV', name: 'Data Governance and Confidentiality', category: 'digital', futureDemand: 0.85, nsqfLevel: 6,
    description: 'Statistical disclosure control, the Collection of Statistics Act, and microdata access policy.',
    tags: ['governance', 'confidentiality', 'sdc', 'privacy'] },

  // Behavioural
  { code: 'REPORT_WRITING', name: 'Statistical Report Writing', category: 'behavioural', futureDemand: 0.6, nsqfLevel: 6,
    description: 'Writing releases and reports that a non-statistician can act on without misreading them.',
    tags: ['writing', 'report', 'release', 'communication'] },
  { code: 'FIELD_SUPERVISION', name: 'Field Team Supervision', category: 'behavioural', futureDemand: 0.5, nsqfLevel: 5,
    description: 'Allocating work, monitoring enumerator quality and resolving field disputes.',
    tags: ['supervision', 'field', 'team', 'monitoring'] },
  { code: 'STAKEHOLDER', name: 'Stakeholder Coordination', category: 'behavioural', futureDemand: 0.7, nsqfLevel: 6,
    description: 'Working with line ministries, state directorates and data users on requirements and releases.',
    tags: ['stakeholder', 'coordination', 'liaison'] },
  { code: 'STAT_ETHICS', name: 'Statistical Ethics and Impartiality', category: 'behavioural', futureDemand: 0.7, nsqfLevel: 6,
    description: 'The Fundamental Principles of Official Statistics in day-to-day decisions.',
    tags: ['ethics', 'impartiality', 'principles', 'integrity'] },
];

/**
 * The role -> competency -> level matrix. `req` keeps each row to one line:
 *   req(competencyCode, requiredLevel, importance, mandatory)
 *
 * Every role carries STAT_ETHICS as mandatory - an official statistician who has
 * not internalised impartiality is a risk regardless of grade - and every role has
 * at least one digital requirement, which is where the workforce gap actually is.
 */
const req = (competency, requiredLevel, importance = 0.5, mandatory = false) => ({
  competency,
  requiredLevel,
  importance,
  mandatory,
});

export const jobRoles = [
  {
    code: 'FI',
    title: 'Field Investigator',
    department: 'NSO_FOD',
    grade: 'Group C',
    description: 'Collects schedule data in the field under a supervisor; the first point at which data quality is won or lost.',
    requirements: [
      req('CENSUS_OPS', 4, 1.0, true),
      req('DATA_QUALITY', 3, 0.9, true),
      req('STAT_ETHICS', 3, 0.8, true),
      req('SURVEY_DESIGN', 2, 0.4),
      req('STAT_PROG', 2, 0.6),
      req('GEOSPATIAL', 2, 0.5),
    ],
  },
  {
    code: 'SI',
    title: 'Senior Investigator / Field Supervisor',
    department: 'NSO_FOD',
    grade: 'Group C',
    description: 'Runs a field team: allocation, spot checks and first-level scrutiny of returned schedules.',
    requirements: [
      req('CENSUS_OPS', 4, 1.0, true),
      req('FIELD_SUPERVISION', 4, 1.0, true),
      req('DATA_QUALITY', 4, 0.9, true),
      req('STAT_ETHICS', 3, 0.8, true),
      req('STAT_PROG', 3, 0.6),
      req('GEOSPATIAL', 3, 0.6),
      req('REPORT_WRITING', 3, 0.5),
    ],
  },
  {
    code: 'JSO',
    title: 'Junior Statistical Officer',
    department: 'NSO_SDRD',
    grade: 'Group B',
    description: 'Tabulation, scrutiny and first-draft estimates for a survey round.',
    requirements: [
      req('SURVEY_DESIGN', 3, 0.9, true),
      req('STAT_INFERENCE', 3, 0.8, true),
      req('DATA_QUALITY', 3, 0.8, true),
      req('STAT_PROG', 3, 0.9, true),
      req('DATA_VIZ', 3, 0.6),
      req('REPORT_WRITING', 3, 0.6),
      req('STAT_ETHICS', 3, 0.7, true),
    ],
  },
  {
    code: 'SSO',
    title: 'Senior Statistical Officer',
    department: 'NSO_SDRD',
    grade: 'Group B',
    description: 'Owns a survey instrument end to end: design, estimation procedure and the published estimate.',
    requirements: [
      req('SURVEY_DESIGN', 4, 1.0, true),
      req('STAT_INFERENCE', 4, 0.9, true),
      req('SMALL_AREA', 3, 0.7),
      req('DATA_QUALITY', 4, 0.8, true),
      req('STAT_PROG', 4, 0.9, true),
      req('DATA_INTEGRATION', 3, 0.7),
      req('REPORT_WRITING', 4, 0.7),
      req('STAT_ETHICS', 4, 0.8, true),
    ],
  },
  {
    code: 'NAO',
    title: 'National Accounts Officer',
    department: 'NSO_NAD',
    grade: 'Group A',
    description: 'Compiles GVA by economic activity and reconciles it against the supply-use framework.',
    requirements: [
      req('NAT_ACCOUNTS', 5, 1.0, true),
      req('ECON_STATS', 4, 0.8, true),
      req('TIME_SERIES', 4, 0.9, true),
      req('DATA_INTEGRATION', 4, 0.8),
      req('STAT_PROG', 3, 0.8),
      req('DATA_VIZ', 3, 0.5),
      req('REPORT_WRITING', 4, 0.7),
      req('STAT_ETHICS', 4, 0.8, true),
    ],
  },
  {
    code: 'PSO',
    title: 'Price Statistics Officer',
    department: 'NSO_PCLD',
    grade: 'Group B',
    description: 'Runs the price collection network and compiles CPI series through base revisions.',
    requirements: [
      req('PRICE_STATS', 5, 1.0, true),
      req('TIME_SERIES', 3, 0.8, true),
      req('DATA_QUALITY', 4, 0.8, true),
      req('BIG_DATA', 3, 0.8),
      req('STAT_PROG', 3, 0.8),
      req('REPORT_WRITING', 3, 0.6),
      req('STAT_ETHICS', 4, 0.8, true),
    ],
  },
  {
    code: 'ESO',
    title: 'Economic Statistics Officer',
    department: 'NSO_ESD',
    grade: 'Group B',
    description: 'Maintains the business register and compiles ASI and IIP aggregates.',
    requirements: [
      req('ECON_STATS', 5, 1.0, true),
      req('DATA_INTEGRATION', 4, 0.9, true),
      req('DATA_QUALITY', 4, 0.8, true),
      req('TIME_SERIES', 3, 0.7),
      req('STAT_PROG', 3, 0.8),
      req('DATA_GOV', 3, 0.7),
      req('STAT_ETHICS', 4, 0.8, true),
    ],
  },
  {
    code: 'DDS',
    title: 'Deputy Director (Statistics)',
    department: 'DES_MH',
    grade: 'Group A',
    description: 'Heads a state statistical unit: district estimates, SDG reporting and coordination with line departments.',
    requirements: [
      req('SDG_MONITOR', 4, 1.0, true),
      req('SMALL_AREA', 4, 0.9, true),
      req('SURVEY_DESIGN', 4, 0.8, true),
      req('DATA_INTEGRATION', 4, 0.8),
      req('STAKEHOLDER', 4, 0.9, true),
      req('DATA_VIZ', 4, 0.7),
      req('STAT_PROG', 3, 0.7),
      req('DATA_GOV', 4, 0.8, true),
      req('STAT_ETHICS', 5, 0.9, true),
    ],
  },
  {
    code: 'SDO',
    title: 'Statistical Data Officer (State)',
    department: 'DES_OD',
    grade: 'Group B',
    description: 'Compiles district-level indicators from departmental returns and state sample rounds.',
    requirements: [
      req('SDG_MONITOR', 4, 0.9, true),
      req('DATA_INTEGRATION', 3, 0.8, true),
      req('DATA_QUALITY', 4, 0.8, true),
      req('GEOSPATIAL', 3, 0.8),
      req('STAT_PROG', 3, 0.8),
      req('DATA_VIZ', 3, 0.7),
      req('STAKEHOLDER', 3, 0.7),
      req('STAT_ETHICS', 3, 0.7, true),
    ],
  },
  {
    code: 'FAC',
    title: 'Faculty / Training Officer',
    department: 'NSSTA',
    grade: 'Group A',
    description: 'Designs and delivers training for the statistical cadre; needs breadth over depth in any one series.',
    requirements: [
      req('SURVEY_DESIGN', 4, 0.8, true),
      req('STAT_INFERENCE', 4, 0.8, true),
      req('STAT_PROG', 4, 0.9, true),
      req('DATA_VIZ', 4, 0.8),
      req('REPORT_WRITING', 4, 0.8, true),
      req('STAKEHOLDER', 4, 0.7),
      req('BIG_DATA', 3, 0.7),
      req('STAT_ETHICS', 5, 0.9, true),
    ],
  },
];

/**
 * The course catalogue. `c(code, targetLevel, weight)` keeps the mapping readable.
 *
 * Levels matter as much as topics: the matcher scores level-fit, so a level-2
 * primer and a level-5 masterclass on the same competency are different products
 * and only one of them is the right next step for a given officer.
 */
const c = (competency, targetLevel, weight = 1) => ({ competency, targetLevel, weight });

export const courses = [
  {
    code: 'IGOT-SAMP-101',
    title: 'Foundations of Sample Survey Design',
    provider: 'iGOT',
    providerCourseId: 'do_31234500001',
    url: 'https://igotkarmayogi.gov.in/course/sample-survey-foundations',
    description: 'Sampling frames, simple and stratified designs, and how a design decision shows up in the final estimate.',
    durationHours: 12,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('SURVEY_DESIGN', 3, 0.8), c('STAT_INFERENCE', 2, 0.2)],
    tags: ['sampling', 'survey', 'frame', 'stratification'],
    rating: 4.4,
    enrolments: 8120,
  },
  {
    code: 'NSSTA-SAMP-401',
    title: 'Complex Survey Estimation and Variance',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/complex-survey-estimation',
    description: 'Weighting, calibration, replication variance and design effects for multi-stage rounds.',
    durationHours: 40,
    modality: 'instructor_led',
    languages: ['English'],
    competencies: [c('SURVEY_DESIGN', 4, 0.5), c('STAT_INFERENCE', 4, 0.5)],
    tags: ['variance', 'calibration', 'weighting', 'design effect'],
    rating: 4.7,
    enrolments: 640,
  },
  {
    code: 'NSSTA-SAE-402',
    title: 'Small Area Estimation for District Indicators',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/small-area-estimation',
    description: 'Fay-Herriot and unit-level models, with the diagnostics needed before a district figure is published.',
    durationHours: 36,
    modality: 'blended',
    languages: ['English'],
    competencies: [c('SMALL_AREA', 4, 0.8), c('STAT_PROG', 3, 0.2)],
    tags: ['small area', 'sae', 'district', 'model based'],
    rating: 4.6,
    enrolments: 310,
  },
  {
    code: 'NSSTA-NAS-501',
    title: 'National Accounts: SNA 2008 in Practice',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/sna-2008',
    description: 'Production, income and expenditure approaches; supply-use balancing and back-series revision.',
    durationHours: 60,
    modality: 'instructor_led',
    languages: ['English'],
    competencies: [c('NAT_ACCOUNTS', 5, 0.9), c('ECON_STATS', 3, 0.1)],
    tags: ['sna', 'gdp', 'gva', 'supply use', 'national accounts'],
    rating: 4.8,
    enrolments: 220,
  },
  {
    code: 'IGOT-NAS-201',
    title: 'Understanding GDP and the National Accounts',
    provider: 'iGOT',
    providerCourseId: 'do_31234500002',
    url: 'https://igotkarmayogi.gov.in/course/understanding-gdp',
    description: 'What the aggregates mean, where the source data comes from, and how to read a revision.',
    durationHours: 8,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('NAT_ACCOUNTS', 2, 1)],
    tags: ['gdp', 'national accounts', 'aggregates'],
    rating: 4.2,
    enrolments: 15400,
  },
  {
    code: 'NSSTA-CPI-403',
    title: 'Price Index Construction and Base Revision',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/price-index-construction',
    description: 'Weighting diagrams, item substitution, quality adjustment and linking across a base change.',
    durationHours: 32,
    modality: 'instructor_led',
    languages: ['English'],
    competencies: [c('PRICE_STATS', 5, 0.85), c('DATA_QUALITY', 3, 0.15)],
    tags: ['cpi', 'wpi', 'index numbers', 'base revision'],
    rating: 4.5,
    enrolments: 280,
  },
  {
    code: 'IGOT-TS-301',
    title: 'Time Series Analysis and Seasonal Adjustment',
    provider: 'iGOT',
    providerCourseId: 'do_31234500003',
    url: 'https://igotkarmayogi.gov.in/course/time-series-seasonal-adjustment',
    description: 'ARIMA identification, X-13ARIMA-SEATS runs, and judging whether an adjustment is defensible.',
    durationHours: 20,
    modality: 'self_paced',
    languages: ['English'],
    competencies: [c('TIME_SERIES', 4, 0.8), c('STAT_PROG', 3, 0.2)],
    tags: ['time series', 'arima', 'x13', 'seasonal adjustment'],
    rating: 4.5,
    enrolments: 3900,
  },
  {
    code: 'IGOT-ASI-202',
    title: 'Industrial Statistics: ASI and IIP',
    provider: 'iGOT',
    providerCourseId: 'do_31234500004',
    url: 'https://igotkarmayogi.gov.in/course/industrial-statistics',
    description: 'Business register maintenance, NIC classification, and the ASI to IIP relationship.',
    durationHours: 16,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('ECON_STATS', 4, 0.8), c('DATA_QUALITY', 3, 0.2)],
    tags: ['asi', 'iip', 'nic', 'business register'],
    rating: 4.1,
    enrolments: 2600,
  },
  {
    code: 'IGOT-SDG-301',
    title: 'SDG Indicators and the National Indicator Framework',
    provider: 'iGOT',
    providerCourseId: 'do_31234500005',
    url: 'https://igotkarmayogi.gov.in/course/sdg-nif',
    description: 'Indicator metadata, source mapping, disaggregation and the reporting cycle.',
    durationHours: 14,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('SDG_MONITOR', 4, 0.85), c('STAKEHOLDER', 3, 0.15)],
    tags: ['sdg', 'nif', 'indicators', 'metadata', 'disaggregation'],
    rating: 4.6,
    enrolments: 6700,
  },
  {
    code: 'NSSTA-ADMIN-404',
    title: 'Administrative Data and Record Linkage',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/administrative-data-integration',
    description: 'Deterministic and probabilistic linkage, match quality assessment, and register-based statistics.',
    durationHours: 28,
    modality: 'blended',
    languages: ['English'],
    competencies: [c('DATA_INTEGRATION', 4, 0.8), c('DATA_GOV', 3, 0.2)],
    tags: ['record linkage', 'administrative data', 'registers', 'integration'],
    rating: 4.4,
    enrolments: 420,
  },
  {
    code: 'IGOT-RPY-101',
    title: 'R and Python for Official Statistics',
    provider: 'iGOT',
    providerCourseId: 'do_31234500006',
    url: 'https://igotkarmayogi.gov.in/course/r-python-official-statistics',
    description: 'From spreadsheet habits to scripted, re-runnable tabulation with version control.',
    durationHours: 24,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('STAT_PROG', 3, 1)],
    tags: ['r', 'python', 'programming', 'reproducible', 'git'],
    rating: 4.7,
    enrolments: 19200,
  },
  {
    code: 'NSSTA-RPY-405',
    title: 'Reproducible Statistical Pipelines',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/reproducible-pipelines',
    description: 'Turning a survey round into a pipeline that another officer can re-run next year without you.',
    durationHours: 30,
    modality: 'blended',
    languages: ['English'],
    competencies: [c('STAT_PROG', 5, 0.7), c('DATA_QUALITY', 4, 0.3)],
    tags: ['pipeline', 'reproducible', 'automation', 'r', 'python'],
    rating: 4.6,
    enrolments: 380,
  },
  {
    code: 'IGOT-VIZ-201',
    title: 'Data Visualisation for Public Dissemination',
    provider: 'iGOT',
    providerCourseId: 'do_31234500007',
    url: 'https://igotkarmayogi.gov.in/course/data-visualisation-dissemination',
    description: 'Chart choice, accessible colour, and dashboards a citizen can read without a statistician present.',
    durationHours: 12,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('DATA_VIZ', 4, 0.85), c('REPORT_WRITING', 3, 0.15)],
    tags: ['visualisation', 'dashboard', 'charts', 'accessibility'],
    rating: 4.5,
    enrolments: 11300,
  },
  {
    code: 'IGOT-GIS-201',
    title: 'Geospatial Methods for Statistical Frames',
    provider: 'iGOT',
    providerCourseId: 'do_31234500008',
    url: 'https://igotkarmayogi.gov.in/course/geospatial-statistical-frames',
    description: 'QGIS basics, geocoding an address frame, spatial joins and boundary changes over time.',
    durationHours: 18,
    modality: 'self_paced',
    languages: ['English'],
    competencies: [c('GEOSPATIAL', 3, 1)],
    tags: ['gis', 'qgis', 'geocoding', 'mapping', 'frames'],
    rating: 4.3,
    enrolments: 5400,
  },
  {
    code: 'NSSTA-BIGD-406',
    title: 'Alternative Data Sources for Official Statistics',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/alternative-data-sources',
    description: 'Web-scraped prices, satellite night-lights and mobility data: fitness for purpose and the bias question.',
    durationHours: 26,
    modality: 'blended',
    languages: ['English'],
    competencies: [c('BIG_DATA', 4, 0.75), c('STAT_PROG', 3, 0.25)],
    tags: ['big data', 'alternative data', 'scraping', 'satellite', 'bias'],
    rating: 4.4,
    enrolments: 470,
  },
  {
    code: 'IGOT-GOV-201',
    title: 'Data Governance, Confidentiality and Disclosure Control',
    provider: 'iGOT',
    providerCourseId: 'do_31234500009',
    url: 'https://igotkarmayogi.gov.in/course/data-governance-confidentiality',
    description: 'The Collection of Statistics Act, microdata release policy and practical disclosure control.',
    durationHours: 10,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('DATA_GOV', 4, 0.8), c('STAT_ETHICS', 3, 0.2)],
    tags: ['governance', 'confidentiality', 'sdc', 'microdata', 'privacy'],
    rating: 4.4,
    enrolments: 7800,
  },
  {
    code: 'IGOT-QUAL-201',
    title: 'Data Quality Assurance and the NQAF',
    provider: 'iGOT',
    providerCourseId: 'do_31234500010',
    url: 'https://igotkarmayogi.gov.in/course/data-quality-nqaf',
    description: 'Edit rules, imputation choices, outlier treatment and documenting quality against the NQAF dimensions.',
    durationHours: 14,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('DATA_QUALITY', 4, 1)],
    tags: ['quality', 'nqaf', 'editing', 'imputation', 'validation'],
    rating: 4.3,
    enrolments: 9100,
  },
  {
    code: 'IGOT-FIELD-101',
    title: 'Field Enumeration and Schedule Canvassing',
    provider: 'iGOT',
    providerCourseId: 'do_31234500011',
    url: 'https://igotkarmayogi.gov.in/course/field-enumeration',
    description: 'Listing, canvassing a schedule, handling refusals, and the checks that catch an error at the door.',
    durationHours: 16,
    modality: 'self_paced',
    languages: ['English', 'Hindi', 'Marathi', 'Odia'],
    competencies: [c('CENSUS_OPS', 4, 0.8), c('DATA_QUALITY', 3, 0.2)],
    tags: ['field', 'enumeration', 'schedule', 'listing', 'canvassing'],
    rating: 4.5,
    enrolments: 24000,
  },
  {
    code: 'NSSTA-SUP-301',
    title: 'Supervising a Field Team',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/field-supervision',
    description: 'Work allocation, spot checks, enumerator feedback and handling a disputed return.',
    durationHours: 20,
    modality: 'blended',
    languages: ['English', 'Hindi'],
    competencies: [c('FIELD_SUPERVISION', 4, 0.8), c('STAKEHOLDER', 3, 0.2)],
    tags: ['supervision', 'field', 'team', 'feedback', 'allocation'],
    rating: 4.4,
    enrolments: 1900,
  },
  {
    code: 'IGOT-WRIT-201',
    title: 'Writing the Statistical Release',
    provider: 'iGOT',
    providerCourseId: 'do_31234500012',
    url: 'https://igotkarmayogi.gov.in/course/writing-statistical-release',
    description: 'Leading with the number, stating the uncertainty, and writing so the figure is not misquoted.',
    durationHours: 10,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('REPORT_WRITING', 4, 0.85), c('STAKEHOLDER', 3, 0.15)],
    tags: ['writing', 'release', 'communication', 'uncertainty'],
    rating: 4.6,
    enrolments: 8600,
  },
  {
    code: 'IGOT-ETH-101',
    title: 'Fundamental Principles of Official Statistics',
    provider: 'iGOT',
    providerCourseId: 'do_31234500013',
    url: 'https://igotkarmayogi.gov.in/course/fundamental-principles',
    description: 'The ten principles, and what each one asks of you when a release is politically inconvenient.',
    durationHours: 6,
    modality: 'self_paced',
    languages: ['English', 'Hindi'],
    competencies: [c('STAT_ETHICS', 4, 1)],
    tags: ['ethics', 'principles', 'impartiality', 'integrity'],
    rating: 4.7,
    enrolments: 21000,
  },
  {
    code: 'NSSTA-COORD-302',
    title: 'Coordinating with Line Departments and Data Users',
    provider: 'NSSTA',
    url: 'https://nssta.gov.in/programmes/stakeholder-coordination',
    description: 'Turning a vague departmental ask into a specification you can actually deliver against.',
    durationHours: 18,
    modality: 'instructor_led',
    languages: ['English'],
    competencies: [c('STAKEHOLDER', 4, 0.8), c('REPORT_WRITING', 3, 0.2)],
    tags: ['stakeholder', 'coordination', 'requirements', 'liaison'],
    rating: 4.2,
    enrolments: 760,
  },
  {
    code: 'INT-INFER-301',
    title: 'Inference Refresher for Serving Officers',
    provider: 'internal',
    description: 'A short internal clinic on estimators, standard errors and what a confidence interval does not say.',
    durationHours: 8,
    modality: 'instructor_led',
    languages: ['English'],
    competencies: [c('STAT_INFERENCE', 3, 1)],
    tags: ['inference', 'standard error', 'confidence interval', 'refresher'],
    rating: 4.0,
    enrolments: 340,
  },
];

/**
 * How far below its roles' requirements each division typically sits, by
 * competency category.
 *
 * This is the one piece of seed data that is openly synthetic, and it exists so the
 * heatmap shows a pattern a viewer can reason about: National Accounts is deep in
 * its own domain and thin on digital; Field Operations is sound operationally and
 * has almost no programming; the state directorates trail on technical method. A
 * grid of random numbers would look the same at a glance and mean nothing.
 *
 * Values are added to the required level, then jittered per officer, then clamped.
 */
export const divisionProfiles = {
  NSO_SDRD: { domain: -0.4, technical: -0.7, digital: -1.5, behavioural: -0.6 },
  NSO_FOD: { domain: -0.3, technical: -1.6, digital: -2.1, behavioural: -0.2 },
  NSO_NAD: { domain: -0.2, technical: -0.6, digital: -1.9, behavioural: -0.9 },
  NSO_PCLD: { domain: -0.5, technical: -1.1, digital: -1.7, behavioural: -1.0 },
  NSO_ESD: { domain: -0.5, technical: -1.3, digital: -1.6, behavioural: -1.1 },
  DES_MH: { domain: -0.9, technical: -1.5, digital: -1.3, behavioural: -0.5 },
  DES_OD: { domain: -1.1, technical: -1.7, digital: -1.8, behavioural: -0.8 },
  NSSTA: { domain: -0.3, technical: -0.5, digital: -1.0, behavioural: -0.2 },
};

/**
 * The two personas the sign-in screen offers as one-click logins. The officer's
 * levels are set explicitly rather than generated: a demo should open on a known
 * state, with a mandatory gap, a high-demand digital gap, and enough already-met
 * requirements that the path is a shortlist and not a wall of red.
 */
export const demoUsers = [
  {
    email: 'rahul.sharma@mospi.gov.in',
    password: 'Officer@123',
    name: 'Rahul Sharma',
    role: 'learner',
    employeeId: 'MOSPI/SSO/2021/0412',
    department: 'NSO_SDRD',
    jobRole: 'SSO',
    xp: 340,
    currentStreak: 7,
    longestStreak: 12,
    learningHours: 32,
    badges: [
      { badgeId: 'first_assessment', title: 'First Assessment', icon: 'Award' },
      { badgeId: '7_day_learner', title: '7 Day Learner', icon: 'Flame' },
    ],
    profile: {
      designation: 'Statistical Officer',
      cadre: 'Subordinate Statistical Service',
      postingLocation: 'Kolkata',
      experienceYears: 5,
      joinedOn: '2021-03-15',
      qualifications: ['M.Sc. Applied Statistics, Calcutta University', 'B.Sc. Mathematics & Statistics'],
      languages: ['English', 'Hindi', 'Bengali'],
    },
    levels: [
      { competency: 'SURVEY_DESIGN', currentLevel: 4, evidence: 'assessment', confidence: 0.85 },
      { competency: 'STAT_PROG', currentLevel: 2, evidence: 'self_reported', confidence: 0.45 },
      { competency: 'DATA_INTEGRATION', currentLevel: 3, evidence: 'assessment', confidence: 0.75 },
      { competency: 'BIG_DATA', currentLevel: 1, evidence: 'self_reported', confidence: 0.35 },
      { competency: 'GEOSPATIAL', currentLevel: 2, evidence: 'self_reported', confidence: 0.4 },
      { competency: 'DATA_VIZ', currentLevel: 3, evidence: 'assessment', confidence: 0.7 },
      { competency: 'STAT_ETHICS', currentLevel: 4, evidence: 'quiz', confidence: 0.9 },
    ],
  },
  {
    email: 'trainer@nssta.gov.in',
    password: 'Trainer@123',
    name: 'Prof. S. Mukherjee',
    role: 'trainer',
    employeeId: 'NSSTA/FAC/2012/0088',
    department: 'NSSTA',
    jobRole: 'FAC',
    xp: 650,
    currentStreak: 15,
    longestStreak: 25,
    learningHours: 85,
    profile: {
      designation: 'Faculty & Assessment Lead',
      cadre: 'Senior Academic Cadre, NSSTA',
      postingLocation: 'Greater Noida',
      experienceYears: 14,
      joinedOn: '2012-04-10',
      qualifications: ['Ph.D. Quantitative Economics, ISI Kolkata', 'M.Stat., ISI Delhi'],
      languages: ['English', 'Hindi', 'Bengali'],
    },
    levels: [],
  },
  {
    email: 'officer@mospi.gov.in',
    password: 'Officer@123',
    name: 'Ananya Rao',
    role: 'learner',
    employeeId: 'MOSPI/SSO/2014/0287',
    department: 'NSO_SDRD',
    jobRole: 'SSO',
    xp: 280,
    currentStreak: 5,
    longestStreak: 9,
    learningHours: 24,
    badges: [
      { badgeId: 'first_assessment', title: 'First Assessment', icon: 'Award' },
    ],
    profile: {
      designation: 'Senior Statistical Officer',
      cadre: 'Indian Statistical Service',
      postingLocation: 'New Delhi',
      experienceYears: 11,
      joinedOn: '2014-08-18',
      qualifications: ['M.Sc. Statistics, University of Hyderabad', 'PG Diploma in Survey Methodology, NSSTA'],
      languages: ['English', 'Hindi', 'Telugu'],
    },
    levels: [
      { competency: 'SURVEY_DESIGN', currentLevel: 4, evidence: 'assessment', confidence: 0.75 },
      { competency: 'STAT_INFERENCE', currentLevel: 3, evidence: 'assessment', confidence: 0.75 },
      { competency: 'SMALL_AREA', currentLevel: 1, evidence: 'self_reported', confidence: 0.4 },
      { competency: 'DATA_QUALITY', currentLevel: 3, evidence: 'assessment', confidence: 0.75 },
      { competency: 'STAT_PROG', currentLevel: 2, evidence: 'self_reported', confidence: 0.4 },
      { competency: 'DATA_INTEGRATION', currentLevel: 1, evidence: 'self_reported', confidence: 0.4 },
      { competency: 'REPORT_WRITING', currentLevel: 4, evidence: 'assessment', confidence: 0.75 },
      { competency: 'STAT_ETHICS', currentLevel: 4, evidence: 'quiz', confidence: 0.9 },
    ],
  },
  {
    email: 'admin@mospi.gov.in',
    password: 'Admin@123',
    name: 'Dr. Vikram Iyer',
    role: 'admin',
    employeeId: 'MOSPI/DDG/2006/0041',
    department: 'NSO_SDRD',
    jobRole: null,
    profile: {
      designation: 'Deputy Director General (Training & Capacity Building)',
      cadre: 'Indian Statistical Service',
      postingLocation: 'New Delhi',
      experienceYears: 19,
      joinedOn: '2006-07-03',
      qualifications: ['Ph.D. Economics, Delhi School of Economics', 'M.Stat., Indian Statistical Institute'],
      languages: ['English', 'Hindi', 'Tamil'],
    },
    levels: [],
  },
];

export const discussionGroups = [
  {
    slug: 'ai-ml',
    title: 'AI & Machine Learning',
    topic: 'Applications of LLMs, predictive modeling, and automated data processing in Official Statistics',
    category: 'technical',
    description: 'Discussion on adopting machine learning algorithms in national accounting, imputation, and survey analytics.',
    icon: 'Brain',
    memberCount: 48,
  },
  {
    slug: 'python-analytics',
    title: 'Python & Data Analytics',
    topic: 'Pandas, NumPy, automation pipelines, and modern reproducible statistical code',
    category: 'technical',
    description: 'Tips and code walkthroughs for transitioning routine tabulation jobs from legacy tools to clean Python.',
    icon: 'Terminal',
    memberCount: 65,
  },
  {
    slug: 'survey-methodology',
    title: 'Survey Methodology',
    topic: 'Sampling frames, dual-frame designs, non-response mitigation, and field schedule design',
    category: 'statistical',
    description: 'Deep-dive peer discussions on NSS rounds, economic census enumeration, and sample optimization.',
    icon: 'BarChart2',
    memberCount: 52,
  },
  {
    slug: 'official-statistics',
    title: 'Official Statistics',
    topic: 'National Accounts (SNA 2008), CPI/WPI revisions, and Fundamental Principles of Official Statistics',
    category: 'statistical',
    description: 'Standards and institutional governance governing statistical releases across Central and State ministries.',
    icon: 'FileText',
    memberCount: 42,
  },
  {
    slug: 'gis-visualization',
    title: 'GIS & Visualization',
    topic: 'Geospatial mapping with QGIS, spatial joins, and interactive statistical dashboards',
    category: 'digital_governance',
    description: 'Techniques for linking administrative polygons and survey data to publish map-based indicators.',
    icon: 'Map',
    memberCount: 38,
  },
  {
    slug: 'data-governance',
    title: 'Data Governance',
    topic: 'Statistical disclosure control (SDC), Collection of Statistics Act, and government cloud',
    category: 'digital_governance',
    description: 'Ensuring privacy and security standards in public microdata releases.',
    icon: 'Shield',
    memberCount: 30,
  },
];

export const officerRoster = [
  { department: 'NSO_SDRD', jobRole: 'SSO', names: ['Meera Krishnan', 'Rajat Bose'] },
  { department: 'NSO_SDRD', jobRole: 'JSO', names: ['Pooja Nair', 'Devendra Yadav', 'Shalini Gupta'] },
  { department: 'NSO_FOD', jobRole: 'SI', names: ['Ramesh Pawar', 'Kavita Deshmukh', 'Imran Sheikh'] },
  { department: 'NSO_FOD', jobRole: 'FI', names: ['Sunil Kamble', 'Geeta Bhosale', 'Anil Jadhav', 'Rekha More', 'Prakash Shinde'] },
  { department: 'NSO_NAD', jobRole: 'NAO', names: ['Suresh Menon', 'Aditi Chatterjee', 'Harish Balan', 'Nandini Iyengar'] },
  { department: 'NSO_PCLD', jobRole: 'PSO', names: ['Vinod Saxena', 'Lakshmi Subramaniam', 'Farhan Qureshi'] },
  { department: 'NSO_ESD', jobRole: 'ESO', names: ['Arvind Trivedi', 'Sneha Kulkarni', 'Mohit Bansal', 'Priyanka Das'] },
  { department: 'DES_MH', jobRole: 'DDS', names: ['Sanjay Patil', 'Vaishali Joshi'] },
  { department: 'DES_MH', jobRole: 'SDO', names: ['Ganesh Sawant', 'Manisha Wagh', 'Tushar Gaikwad'] },
  { department: 'DES_OD', jobRole: 'SDO', names: ['Bijay Mohanty', 'Sasmita Panda', 'Rabindra Behera', 'Jyotsna Sahu'] },
  { department: 'NSSTA', jobRole: 'FAC', names: ['Dr. Anita Raghavan', 'Dr. Sameer Kulkarni', 'Neha Bhatt'] },
];
